name: Run tests

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ./server/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ./server

      - name: Install dependencies
        run: npx playwright install
        working-directory: ./server

      - name: Run Tests
        run: npm run test
        working-directory: ./server