name: Run tests

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 19
        uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: npm
          cache-dependency-path: ./pixelpact/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ./pixelpact

      - name: Run Tests
        run: npm run test
        working-directory: ./pixelpact